### ISSUE TITLE
Exception if $html is empty in SvgStoreService->process

### ISSUE THREAD

**Issue by aschmutt** [lochmueller/sourceopt#115]
I got an exception in `SvgStoreService->process(string $html)` because $html is empty (`$html=''`)

Exact reason I couldn't find, last thing I added was SystemEmail from EXT:form, so maybe it has something to do with Mail Template. 
But I couldn't reproduce on local ddev, only on Production. Or could be database differences, I don't know. 

But checking for empty string is easy and fixes the exception: 
```    
public function process(string $html): string
    {
        if (strlen($html) == 0) {
            return '';
        }
```
There might be other places, this should be checked by someone who knows the extension better. 

<img width="1156" alt="Bildschirmfoto 2023-01-28 um 23 24 47" src="https://user-images.githubusercontent.com/1215504/215293967-bf64eeab-185a-4d81-b57f-ce6e04086d05.png">

**Comment by aschmutt** [comment]
Patch File - add in composer with `cweagans/composer-patches`: 
[sourceopt.patch](https://github.com/lochmueller/sourceopt/files/10528478/sourceopt.patch)
``` 
"extra": {
    "patches": {
        "lochmueller/sourceopt": {
            "Bugfix SvgStoreService for empty html": "build/patches/sourceopt.patch"
        }
    }
},
```

**Comment by xerc** [comment]
hey @aschmutt ; may please check why `$response->getBody()` is emtpy
@ https://github.com/lochmueller/sourceopt/blob/master/Classes/Middleware/SvgStoreMiddleware.php#L33-L34

**Comment by lochmueller** [comment]
Hey @xerc ,
I suggest: Do not call "__toString()" manually. Instead you can just cast to string and the problem is gone (if this location is the problem).
Regards,
Tim

**Comment by xerc** [comment]
should not go so far (preg_match) therefore we need to know whats inside
ref. https://github.com/lochmueller/sourceopt/blob/master/Classes/Service/SvgStoreService.php#L48

**Comment by lochmueller** [comment]
For what is `5 == \count($dom)` in this context? If the preg do not match, the count have to be 5. Otherwise the return statement is not executred. Could you change the magic number 5 to a speaking name constant?

**Comment by xerc** [comment]
> For what is `5 == \count($dom)` in this context?
> If the preg do not match, the count have to be 5. Otherwise the return statement is not executred.

IF preg fails `return` is executed
IF preg works there need to be 5 array-entries; 0,1,2,'head','body' => prevents <head> | <body> only to be present

**Comment by lochmueller** [comment]
Hmm... sound strange. If the REGEX match, it should always this count, otherwise the regex would not match. I think `preg_match() !== 1` should be enough, because the regex do not match: https://www.php.net/manual/de/function.preg-match.php#refsect1-function.preg-match-returnvalues

**Comment by xerc** [comment]
i vagly remember to put it in to enshure the array-size but lets remove it

**Comment by aschmutt** [comment]
> hey @aschmutt ; may please check why `$response->getBody()` is emtpy
> @ https://github.com/lochmueller/sourceopt/blob/master/Classes/Middleware/SvgStoreMiddleware.php#L33-L34

@xerc this is the requested debug output of the middleware $request and $response: 
<img width="1076" alt="Bildschirmfoto 2023-01-30 um 22 38 55" src="https://user-images.githubusercontent.com/1215504/215601440-099cd5d2-d8b9-4802-8235-950bc73240ec.png">

**Comment by aschmutt** [comment]
And this is my form finisher yaml for the redirect after submit: 
```
finishers:
    -
        options:
            subject: 'Anfrage'
            recipients:
                kontakt@auxweb.de: 'AuxWeb GmbH'
            senderAddress: kontakt@auxweb.de
            senderName: 'AuxWeb GmbH'
            addHtmlPart: true
            attachUploads: false
            translation:
                language: Default
            useFluidEmail: true
            title: ''
        identifier: EmailToReceiver
    -
        options:
            subject: 'Ihre Anfrage'
            recipients:
                '{email}': '{name}'
            senderAddress: kontakt@auxweb.de
            senderName: AuxWeb
            addHtmlPart: true
            attachUploads: false
            useFluidEmail: true
            title: ''
        identifier: EmailToSender
    -
        options:
            pageUid: '89'
            additionalParameters: ''
        identifier: Redirect
```
pageUid 89 exists and is correctly identified in dump as: `https://www.auxweb.de/typo3-update/vielen-dank`
